// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Silica$Silica = require("../Silica.bs.js");

var animals = /* :: */[
  "macan",
  /* :: */[
    "hiu",
    /* :: */[
      "kura-kura",
      /* :: */[
        "panda",
        /* [] */0
      ]
    ]
  ]
];

var bodyStyle = "style=\"margin: 0; padding: 0; box-sizing: border-box;\"";

var articleStyle = "style=\"background: pink; color: white;\"";

var listAnimal = List.map((function (animal) {
        return Silica$Silica.HTML.li("", Silica$Silica.HTML.text(animal));
      }), animals);

var head = Silica$Silica.HTML.head("", /* :: */[
      Silica$Silica.HTML.title("", Silica$Silica.HTML.text("Aerogel SSG")),
      /* [] */0
    ]);

var body = Silica$Silica.HTML.body(bodyStyle, /* :: */[
      Silica$Silica.HTML.h1("", Silica$Silica.HTML.text("THIS IS THE AEROGEL SSG")),
      /* :: */[
        Silica$Silica.HTML.article(articleStyle, /* :: */[
              "note: this is allowed",
              /* :: */[
                Silica$Silica.HTML.ol("style=\"padding: 20px 0;\"", listAnimal),
                /* [] */0
              ]
            ]),
        /* [] */0
      ]
    ]);

var footer = Silica$Silica.HTML.footer("", /* :: */[
      Silica$Silica.HTML.p("", Silica$Silica.HTML.text("made with " + "❤️")),
      /* [] */0
    ]);

var main = Silica$Silica.HTML.html("", /* :: */[
      head,
      /* :: */[
        body,
        /* :: */[
          footer,
          /* [] */0
        ]
      ]
    ]);

console.log(main);

var S = /* alias */0;

var oper = 6;

exports.S = S;
exports.animals = animals;
exports.bodyStyle = bodyStyle;
exports.articleStyle = articleStyle;
exports.listAnimal = listAnimal;
exports.oper = oper;
exports.head = head;
exports.body = body;
exports.footer = footer;
exports.main = main;
/* listAnimal Not a pure module */
