// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function render(tag, attrs, children) {
  var elem = List.fold_left((function (a, b) {
          return a + b;
        }), List.hd(children), List.tl(children));
  return "<" + (String(tag) + (" " + (String(attrs) + (">" + (String(elem) + ("</" + (String(tag) + ">")))))));
}

var Core = {
  render: render
};

function text(node) {
  return /* :: */[
          node,
          /* [] */0
        ];
}

function a(attrs, children) {
  return render("a", attrs, children);
}

function abbr(attrs, children) {
  return render("abbr", attrs, children);
}

function address(attrs, children) {
  return render("address", attrs, children);
}

function area(attrs, children) {
  return render("area", attrs, children);
}

function article(attrs, children) {
  return render("article", attrs, children);
}

function aside(attrs, children) {
  return render("aside", attrs, children);
}

function audio(attrs, children) {
  return render("audio", attrs, children);
}

function b(attrs, children) {
  return render("b", attrs, children);
}

function base(attrs, children) {
  return render("base", attrs, children);
}

function bdi(attrs, children) {
  return render("bdi", attrs, children);
}

function bdo(attrs, children) {
  return render("bdo", attrs, children);
}

function blockquotes(attrs, children) {
  return render("blockquotes", attrs, children);
}

function body(attrs, children) {
  return render("body", attrs, children);
}

function br(attrs, children) {
  return render("br", attrs, children);
}

function button(attrs, children) {
  return render("button", attrs, children);
}

function canvas(attrs, children) {
  return render("canvas", attrs, children);
}

function caption(attrs, children) {
  return render("caption", attrs, children);
}

function cite(attrs, children) {
  return render("cite", attrs, children);
}

function code(attrs, children) {
  return render("code", attrs, children);
}

function col(attrs, children) {
  return render("col", attrs, children);
}

function colgroup(attrs, children) {
  return render("colgroup", attrs, children);
}

function command(attrs, children) {
  return render("command", attrs, children);
}

function datalist(attrs, children) {
  return render("datalist", attrs, children);
}

function dd(attrs, children) {
  return render("dd", attrs, children);
}

function del(attrs, children) {
  return render("del", attrs, children);
}

function details(attrs, children) {
  return render("details", attrs, children);
}

function dfn(attrs, children) {
  return render("dfn", attrs, children);
}

function dialog(attrs, children) {
  return render("dialog", attrs, children);
}

function div(attrs, children) {
  return render("div", attrs, children);
}

function dl(attrs, children) {
  return render("dl", attrs, children);
}

function dt(attrs, children) {
  return render("dt", attrs, children);
}

function em(attrs, children) {
  return render("em", attrs, children);
}

function embed(attrs, children) {
  return render("embed", attrs, children);
}

function figcation(attrs, children) {
  return render("figcation", attrs, children);
}

function figure(attrs, children) {
  return render("figure", attrs, children);
}

function footer(attrs, children) {
  return render("footer", attrs, children);
}

function form(attrs, children) {
  return render("form", attrs, children);
}

function h1(attrs, children) {
  return render("h1", attrs, children);
}

function h2(attrs, children) {
  return render("h2", attrs, children);
}

function h3(attrs, children) {
  return render("h3", attrs, children);
}

function h4(attrs, children) {
  return render("h4", attrs, children);
}

function h5(attrs, children) {
  return render("h5", attrs, children);
}

function h6(attrs, children) {
  return render("h6", attrs, children);
}

function head(attrs, children) {
  return render("head", attrs, children);
}

function header(attrs, children) {
  return render("header", attrs, children);
}

function hr(attrs, children) {
  return render("hr", attrs, children);
}

function html(attrs, children) {
  return render("html", attrs, children);
}

function i(attrs, children) {
  return render("i", attrs, children);
}

function iframe(attrs, children) {
  return render("iframe", attrs, children);
}

function img(attrs, children) {
  return render("img", attrs, children);
}

function input(attrs, children) {
  return render("input", attrs, children);
}

function ins(attrs, children) {
  return render("ins", attrs, children);
}

function kbd(attrs, children) {
  return render("kbd", attrs, children);
}

function label(attrs, children) {
  return render("label", attrs, children);
}

function legend(attrs, children) {
  return render("legend", attrs, children);
}

function li(attrs, children) {
  return render("li", attrs, children);
}

function link(attrs, children) {
  return render("link", attrs, children);
}

function main(attrs, children) {
  return render("main", attrs, children);
}

function map(attrs, children) {
  return render("map", attrs, children);
}

function mark(attrs, children) {
  return render("mark", attrs, children);
}

function menu(attrs, children) {
  return render("menu", attrs, children);
}

function menuItem(attrs, children) {
  return render("menuItem", attrs, children);
}

function meta(attrs, children) {
  return render("meta", attrs, children);
}

function meter(attrs, children) {
  return render("meter", attrs, children);
}

function nav(attrs, children) {
  return render("nav", attrs, children);
}

function noscript(attrs, children) {
  return render("noscript", attrs, children);
}

function object_(attrs, children) {
  return render("object", attrs, children);
}

function ol(attrs, children) {
  return render("ol", attrs, children);
}

function optgroup(attrs, children) {
  return render("optgroup", attrs, children);
}

function p(attrs, children) {
  return render("p", attrs, children);
}

function param(attrs, children) {
  return render("param", attrs, children);
}

function pre(attrs, children) {
  return render("pre", attrs, children);
}

function q(attrs, children) {
  return render("q", attrs, children);
}

function rp(attrs, children) {
  return render("rp", attrs, children);
}

function rt(attrs, children) {
  return render("rt", attrs, children);
}

function ruby(attrs, children) {
  return render("ruby", attrs, children);
}

function samp(attrs, children) {
  return render("samp", attrs, children);
}

function script(attrs, children) {
  return render("script", attrs, children);
}

function section(attrs, children) {
  return render("section", attrs, children);
}

function select(attrs, children) {
  return render("select", attrs, children);
}

function small(attrs, children) {
  return render("small", attrs, children);
}

function source(attrs, children) {
  return render("source", attrs, children);
}

function span(attrs, children) {
  return render("span", attrs, children);
}

function strong(attrs, children) {
  return render("strong", attrs, children);
}

function style(attrs, children) {
  return render("style", attrs, children);
}

function sub(attrs, children) {
  return render("sub", attrs, children);
}

function summary(attrs, children) {
  return render("summary", attrs, children);
}

function sup(attrs, children) {
  return render("sup", attrs, children);
}

function table(attrs, children) {
  return render("table", attrs, children);
}

function tbody(attrs, children) {
  return render("tbody", attrs, children);
}

function td(attrs, children) {
  return render("td", attrs, children);
}

function textarea(attrs, children) {
  return render("textarea", attrs, children);
}

function tfoot(attrs, children) {
  return render("tfoot", attrs, children);
}

function th(attrs, children) {
  return render("th", attrs, children);
}

function thead(attrs, children) {
  return render("thead", attrs, children);
}

function time(attrs, children) {
  return render("time", attrs, children);
}

function title(attrs, children) {
  return render("title", attrs, children);
}

function tr(attrs, children) {
  return render("tr", attrs, children);
}

function track(attrs, children) {
  return render("track", attrs, children);
}

function u(attrs, children) {
  return render("u", attrs, children);
}

function $$var(attrs, children) {
  return render("var", attrs, children);
}

function video(attrs, children) {
  return render("video", attrs, children);
}

function wbr(attrs, children) {
  return render("wbr", attrs, children);
}

var HTML = {
  text: text,
  a: a,
  abbr: abbr,
  address: address,
  area: area,
  article: article,
  aside: aside,
  audio: audio,
  b: b,
  base: base,
  bdi: bdi,
  bdo: bdo,
  blockquotes: blockquotes,
  body: body,
  br: br,
  button: button,
  canvas: canvas,
  caption: caption,
  cite: cite,
  code: code,
  col: col,
  colgroup: colgroup,
  command: command,
  datalist: datalist,
  dd: dd,
  del: del,
  details: details,
  dfn: dfn,
  dialog: dialog,
  div: div,
  dl: dl,
  dt: dt,
  em: em,
  embed: embed,
  figcation: figcation,
  figure: figure,
  footer: footer,
  form: form,
  h1: h1,
  h2: h2,
  h3: h3,
  h4: h4,
  h5: h5,
  h6: h6,
  head: head,
  header: header,
  hr: hr,
  html: html,
  i: i,
  iframe: iframe,
  img: img,
  input: input,
  ins: ins,
  kbd: kbd,
  label: label,
  legend: legend,
  li: li,
  link: link,
  main: main,
  map: map,
  mark: mark,
  menu: menu,
  menuItem: menuItem,
  meta: meta,
  meter: meter,
  nav: nav,
  noscript: noscript,
  object_: object_,
  ol: ol,
  optgroup: optgroup,
  p: p,
  param: param,
  pre: pre,
  q: q,
  rp: rp,
  rt: rt,
  ruby: ruby,
  samp: samp,
  script: script,
  section: section,
  select: select,
  small: small,
  source: source,
  span: span,
  strong: strong,
  style: style,
  sub: sub,
  summary: summary,
  sup: sup,
  table: table,
  tbody: tbody,
  td: td,
  textarea: textarea,
  tfoot: tfoot,
  th: th,
  thead: thead,
  time: time,
  title: title,
  tr: tr,
  track: track,
  u: u,
  $$var: $$var,
  video: video,
  wbr: wbr
};

exports.Core = Core;
exports.HTML = HTML;
/* No side effect */
